---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bank-arc-frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: front
        image: arcepamcr.azurecr.io/bank-of-anthos-frontend:v1
        volumeMounts:
        - name: publickey
          mountPath: "/root/.ssh"
          readOnly: true
        env:
        - name: VERSION
          value: "v0.1.0"
        - name: PORT
          value: "8080"
        - name: TRANSACTIONS_API_ADDR
          value: "ledgerwriter.bank-arc-backend.global:6060"
        - name: BALANCES_API_ADDR
          value: "balancereader.bank-arc-backend.global:7000"
        - name: HISTORY_API_ADDR
          value: "transactionhistory.bank-arc-backend.global:7070"
        - name: CONTACTS_API_ADDR
          value: "contacts.bank-arc-frontend.svc.cluster.local:8080"
        - name: USERSERVICE_API_ADDR
          value: "userservice.bank-arc-frontend.svc.cluster.local:5050"
        - name: LOCAL_ROUTING_NUM
          value: "123456789"
        - name: PUB_KEY_PATH
          value: "/root/.ssh/publickey"
        - name: DEFAULT_USERNAME
          value: "testuser"
        - name: DEFAULT_PASSWORD
          value: "password"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: frontend-secret
      volumes:
      - name: publickey
        secret:
          secretName: jwt-key
          items:
          - key: jwtRS256.key.pub
            path: publickey
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bank-arc-frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
