---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancereader
spec:
  selector:
    matchLabels:
      app: balancereader
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: balancereader
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: reader
        image: gcr.io/bank-of-anthos/balancereader:v0.1.0
        volumeMounts:
        - name: publickey
          mountPath: "/root/.ssh"
          readOnly: true
        env:
        - name: VERSION
          value: "v0.1.0"
        - name: PORT
          value: "7000"
        - name: LOCAL_ROUTING_NUM
          value: "123456789"
        - name: PUB_KEY_PATH
          value: "/root/.ssh/publickey"
        - name: POLL_MS
          value: "100"
        - name: CACHE_SIZE
          value: "1000000"
        # tell Java to obey container memory limits
        - name: JVM_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
        envFrom:
        # add ledger-db credentials from ConfigMap
        - configMapRef:
            name: ledger-db-config
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 300m
        readinessProbe:
          httpGet:
            path: /ready
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthy
            port: 7000
          initialDelaySeconds: 120
          periodSeconds: 5
      volumes:
      - name: publickey
        secret:
          secretName: jwt-key
          items:
          - key: jwtRS256.key.pub
            path: publickey
---
apiVersion: v1
kind: Service
metadata:
  name: balancereader
spec:
  type: ClusterIP
  selector:
    app: balancereader
  ports:
  - name: http
    port: 7000
    targetPort: 7000

