---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-db
spec:
  selector:
    matchLabels:
      app: ledger-db
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: ledger-db
    spec:
      containers:
        - name: postgres
          image: gcr.io/bank-of-anthos/ledger-db:v0.1.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: USE_DEFAULT_DATA
              value: "True"
            - name: LOCAL_ROUTING_NUM
              value: "123456789"
            - name: DEFAULT_ACCOUNT
              value: "7595821437"
            - name: DEFAULT_DEPOSIT_ACCOUNT
              value: "6029390231"
            - name: DEFAULT_DEPOSIT_ROUTING
              value: "295164083"
          envFrom:
            - configMapRef:
                name: ledger-db-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-db-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-db:5432/postgresdb
  SPRING_DATASOURCE_USERNAME: admin # should match POSTGRES_USER
  SPRING_DATASOURCE_PASSWORD: password # should match POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-db
spec:
  type: ClusterIP
  selector:
    app: ledger-db
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
